# Generated by Django 5.0.4 on 2024-05-04 21:16

import colorfield.fields
import mdeditor.fields
from django.db import migrations, models

import apps.issues.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default=apps.issues.models.generate_hex_color, image_field=None, max_length=25, samples=None
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", mdeditor.fields.MDTextField(blank=True, null=True)),
                (
                    "tags",
                    models.ManyToManyField(blank=True, db_table="issues_tags", related_name="issues", to="issues.tag"),
                ),
            ],
            options={
                "db_table": "issues",
                "ordering": ["-created"],
            },
        ),
    ]
